force-app/main/default/objects/CustomCheckoutValidation__c/CustomCheckoutValidation__c.object-meta.xml
<CustomObject>
    <label>Custom Checkout Validation</label>
    <nameField>
        <displayFormat>CCV-{00000}</displayFormat>
        <label>Custom Checkout Validation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Checkout Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomCheckoutValidation__c/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <description>Programmatic validation - reference an apex class validation extension.</description>
    <inlineHelpText>Reference an apex class validation extension.</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomCheckoutValidation__c/fields/FlowApiName__c.field-meta.xml
<CustomField>
    <fullName>FlowApiName__c</fullName>
    <description>Programmatic validation - reference a flow validation extension.</description>
    <inlineHelpText>Reference a flow validation extension.</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomCheckoutValidation__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message to be displayed when validation rule blocks an order checkout.</description>
    <inlineHelpText>Message to be displayed when validation rule blocks an order checkout.</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomCheckoutValidation__c/fields/ValidatedField__c.field-meta.xml
<CustomField>
    <fullName>ValidatedField__c</fullName>
    <description>API Name of Order field to validate.</description>
    <inlineHelpText>Specify the Order field (API Name) to validate.</inlineHelpText>
    <label>Validated Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomCheckoutValidation__c/fields/ValidationOperator__c.field-meta.xml
<CustomField>
    <fullName>ValidationOperator__c</fullName>
    <description>Operator to compare the Validated Field against the Validation Value.</description>
    <inlineHelpText>Select the Operator to compare the Validated Field against the Validation Value.</inlineHelpText>
    <label>Validation Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValidationOperator</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomCheckoutValidation__c/fields/ValidationValue__c.field-meta.xml
<CustomField>
    <fullName>ValidationValue__c</fullName>
    <description>Value that will be compared against the Validated Field</description>
    <inlineHelpText>Specify the validation value that will be compared against the Validated Field.</inlineHelpText>
    <label>Validation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ValidationOperator.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Equals</fullName>
    </customValue>
    <customValue>
        <fullName>Not Equals</fullName>
    </customValue>
    <customValue>
        <fullName>Contains</fullName>
    </customValue>
    <customValue>
        <fullName>Greater Than</fullName>
    </customValue>
    <customValue>
        <fullName>Less Than</fullName>
    </customValue>
    <customValue>
        <fullName>Not Empty</fullName>
    </customValue>
    <customValue>
        <fullName>Is Empty</fullName>
    </customValue>
    <masterLabel>Validation Operator</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomCheckoutValidationsSelector_mp.cls
public with sharing class CustomCheckoutValidationsSelector_mp {

    public static List<CustomCheckoutValidation__c> selectActiveValidations() {
        return [
            SELECT
                Id,
                Name,
                RecordType.DeveloperName,
                ApexClassName__c,
                FlowApiName__c,
                ValidatedField__c,
                ValidationOperator__c,
                ValidationValue__c,
                Message__c
            FROM CustomCheckoutValidation__c
            WHERE Active__c = true
            WITH SECURITY_ENFORCED
        ];
    }
}